def handle_error(error):
    response = error.to_response()
    return response
